[package]
name = "serde_int_map"
version = "0.1.0"
description = "General traits for serde_int_map_derive"
license = "MIT"
authors = ["Patrick Uiterwijk <patrick@puiterwijk.org>"]
edition = "2018"

[lib]
